@baseUrl = http://localhost:3002

# @name send-message
POST {{baseUrl}}/api/messages
Content-Type: application/json

{
  "question": "Qual foi o meu primeiro emprego?"
}

###

# @name list-messages
GET {{baseUrl}}/api/messages
Content-Type: application/json

{}

###

# @name delete-messages
DELETE {{baseUrl}}/api/messages
Content-Type: application/json

{}

###

# @name list-uploads
GET {{baseUrl}}/api/uploads
Content-Type: application/json

{}